#===== Conf. settings for all YDB cluster nodes =======#
ansible_python_interpreter: /usr/bin/python3           # Path to Python interpreter
ydb_unpack_options: "--strip-component=1"              # Options for unpacking YDB

#============== YDB software version setup ============#
ydb_version: 23.1.26                                   # YDB server software release version
ydb_archive: ydbd-{{ ydb_version }}-linux-amd64.tar.gz # YDB server software archive name
ydb_download_url: https://binaries.ydb.tech/release/{{ ydb_version }}/{{ ydb_archive }} # URL for downloading YDB software

#========== YDB installation directories setup ========#
ydb_dir: /opt/ydb                                      # Directory for YDB software installation
cfg_path: "{{ ydb_dir }}/cfg"
lib_path: "{{ ydb_dir }}/release/{{ ydb_version }}/lib"

#================== Base setup ========================#
ydb_domain: Root                                       # YDB cluster domain (aka cluster identifier), 'Root' as per documentation
ydb_dbname: testdb                                     # Database name for the dynamic nodes

#================ Network setup =======================#
inner_net: 127.0.0.1


#================= Nodes config setup ===============#
config_src: '{{ playbook_dir }}/roles/prepare_ydb_config/templates/src/config/'
config_tmp: '{{ playbook_dir }}/roles/prepare_ydb_config/templates/tmp/config/'
final_config_template: '{{ playbook_dir }}/roles/prepare_ydb_config/templates/config.j2'
configs_parts: ['host_configs.j2','hosts.j2','actor_system_config.j2','blob_storage_config.j2','channel_profile_config.j2','domains_config.j2','grpc_config.j2','monitoring_config.j2', 'shared_cached_config.j2','table_service_config.j2']
list_of_files: "{{ configs_parts | map('regex_replace', '^', config_tmp) | list }}"


#================= Nodes service setup ===============#
service_src: '{{ playbook_dir }}/roles/configuration_dyn_nodes/templates/src/dynnode-service/'
service_tmp: '{{ playbook_dir }}/roles/configuration_dyn_nodes/templates/tmp/'
final_service_template: '{{ playbook_dir }}/roles/configuration_dyn_nodes/templates/dynnode-service.j2'
service_parts: ['Unit.j2','Service_part_1.j2','Service_part_2.j2','Install.j2']
list_of_service_files: "{{ service_parts | map('regex_replace', '^', service_src) | list }}"