---
#============= Establish SSH tunnel and display connection URL ==========#
- name: Get list of available shells from /etc/shells
  ansible.builtin.command: cat /etc/shells
  register: shell_output
  delegate_to: localhost
  become: false
  
- name: Set active shell to bash or zsh if available
  set_fact:
    active_shell: "{{ '/bin/bash' if '/bin/bash' in shell_output.stdout else '/bin/zsh' if '/bin/zsh' in shell_output.stdout else omit }}"

- name: Establish an SSH tunnel to the YDB monitoring port
  delegate_to: localhost
  become: false
  ansible.builtin.shell: 
    cmd: "ssh  -f -L {{ hostvars[groups['ydb-static-node'][0]]['mon_port'] }}:localhost:{{ hostvars[groups['ydb-static-node'][0]]['mon_port'] }} -N -i {{ ansible_ssh_private_key_file }} -vvv {{ ansible_ssh_user }}@{{ inventory_hostname }}"
    executable: "{{ active_shell }}"
  async: 15
  poll: 0
  when: inventory_hostname in groups['ydb-static-node'][0]

- name: Display the YDB monitoring connection URL
  ansible.builtin.debug:
    msg: "Now you can connect to YDB monitoring via this URL: http://localhost:{{ hostvars[groups['ydb-static-node'][0]]['mon_port'] }}"
  when: inventory_hostname in groups['ydb-static-node'][0]