---
#================== Preparing YDB folder structure ==================#
- name: Create the ydb group
  group: name=ydb system=true

- name: Create the ydb user with disk group access
  user: 
    name: ydb
    group: ydb 
    groups: disk 
    system: true 
    create_home: true 
    home: "{{ ydb_dir }}/home"
    comment: "YDB Service Account"

- name: Create the Ansible remote_tmp for the ydb user
  file:
    path: "{{ ydb_dir }}/home/.ansible/tmp"
    state: directory
    recurse: true
    group: ydb
    owner: ydb

#================== Creating YDB directories ==================#

- name: Create the YDB release directory
  file: state=directory path={{ ydb_dir }}/release group=bin owner=root mode=755

- name: Create the YDB configuration directory
  file: state=directory path={{ cfg_path }} group=ydb owner=ydb mode=755

- name: Create the YDB audit directory
  file: state=directory path={{ ydb_dir }}/audit group=ydb owner=ydb mode=700

- name: Create the YDB certs directory
  file: state=directory path={{ ydb_dir }}/certs group=ydb owner=ydb mode=700

- name: Create the YDB configuration backup directory
  file: state=directory path={{ ydb_dir }}/reserve group=ydb owner=ydb mode=700

- name: Create the YDB server binary directory for the specified version
  file: state=directory
        path="{{ ydb_dir }}/release/{{ ydb_version }}"
        recurse=true
        group=bin
        owner=root

#================== Downloading and installing YDB ==================#

- name: Download the YDB sources archive
  get_url: url={{ ydb_download_url }} dest={{ ydb_dir }}/release/{{ ydb_version }}/{{ ydb_archive }}

- name: Set owner and group for the YDB sources archive
  file: 
        path="{{ ydb_dir }}/release/{{ ydb_version }}/{{ ydb_archive }}"
        group=bin
        owner=root  

- name: Install the YDB server binary package
  ansible.builtin.unarchive:
    remote_src: yes
    creates: "{{ ydb_dir }}/release/{{ ydb_version }}/bin/ydbd"
    dest: "{{ ydb_dir }}/release/{{ ydb_version }}"
    group: bin
    owner: root
    src: "{{ ydb_dir }}/release/{{ ydb_version }}/{{ ydb_archive }}"
    extra_opts: "{{ ydb_unpack_options }}"

- name: Create the YDB CLI default binary directory
  file: state=directory path={{ ydb_dir }}/home/ydb/bin recurse=true group=ydb owner=ydb mode=700


# ===========Setup ports forwarding========== 

- name: Enable IP forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes

- name: Forward multiple ports to localhost
  iptables:
    table: nat
    chain: PREROUTING
    jump: DNAT
    to_destination: "{{ inner_net }}:{{ item }}"
    destination: "{{ ansible_host }}"
    protocol: tcp
    match: tcp
    destination_port: "{{ item }}"
  loop:
    - "{{ ic_port }}"
    - "{{ grpc_port }}"
    - "{{ mon_port }}"


