---
#============= Configuration dynamic nodes =============

- name: Generate node-broker list
  template:
    src: "{{ service_src }}node-broker.j2"
    dest: "{{ service_tmp }}node-broker.j2"
  delegate_to: localhost
  become: no
  when: inventory_hostname in groups['ydb-dyn-node'][0]

- name: Вставка {{ service_tmp }}node-broker.j2 как предпоследнего элемента
  set_fact:
    list_of_service_files: "{{ list_of_service_files[:-2] + [service_tmp + 'node-broker.j2'] + list_of_service_files[-2:] }}"  

- name: Initialize an empty string for file content
  set_fact:
    combined_content: ""
    is_first_iteration: true

- name: Slurp content of each file and append
  ansible.builtin.slurp:
    src: "{{ item }}"
  register: slurped_content
  loop: "{{ list_of_service_files }}"
  delegate_to: localhost
  become: no
  loop_control:
    label: "{{ item }}"

- name: Combine file content
  set_fact:
    combined_content: "{{ combined_content + ('\n') + (item.content | b64decode) }}"
  loop: "{{ slurped_content.results }}"

- name: Copy the combined content to the target file
  ansible.builtin.copy:
    dest: "{{ final_service_template }}"
    content: "{{ combined_content }}"
  delegate_to: localhost
  become: no
  when: inventory_hostname in groups['ydb-dyn-node'][0]

- name: Copy dynnode service to hosts
  template:
    src: "{{ final_service_template }}"
    dest: "/etc/systemd/system/ydbd-dynamic.service"
  when: inventory_hostname in groups['ydb-dyn-node']

- name: Refresh systemd configuration to recognize dynamic node service
  ansible.builtin.systemd:
    daemon_reload: true
  when: inventory_hostname in groups['ydb-dyn-node']

- name: Start the YDB dynamic node service
  become: true
  ansible.builtin.systemd:
    state: started
    name: ydbd-dynamic
  any_errors_fatal: true    
  when: inventory_hostname in groups['ydb-dyn-node']

- name: Verify that the YDB storage node service is active
  shell: systemctl is-active ydbd-dynamic || true
  register: ydbd_dynamic_status
  any_errors_fatal: true
  retries: 5
  delay: 10
  until: ydbd_dynamic_status.stdout == "active"
  when: inventory_hostname in groups['ydb-dyn-node']