---

#============= Configuration storage nodes ============= 
- name: Upload service for static nodes
  template:
    src: "{{ playbook_dir }}/roles/configuration_static_nodes/templates/src/static-service.j2"
    dest: "/etc/systemd/system/ydbd-storage.service"
  when: inventory_hostname in groups['ydb-static-node']

- name: Refresh systemd configuration to recognize new services
  ansible.builtin.systemd:
    daemon_reload: true
  when: inventory_hostname in groups['ydb-static-node']

- name: Start the YDB storage node service
  become: true
  ansible.builtin.systemd:
    state: started
    name: ydbd-storage
  any_errors_fatal: true    
  when: inventory_hostname in groups['ydb-static-node']

- name: Verify that the YDB storage node service is active
  shell: systemctl is-active ydbd-storage || true
  register: ydbd_storage_status
  any_errors_fatal: true
  retries: 5
  delay: 10
  until: ydbd_storage_status.stdout == "active"
  when: inventory_hostname in groups['ydb-static-node']

- name: Debug ydbd_storage_status
  debug:
    var: ydbd_storage_status.stdout
  when: inventory_hostname in groups['ydb-static-node']